# Generated by Django 4.2.7 on 2023-11-05 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
